name: Build Docker Image

on:
  push:
    tags:
    - v*

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        type: choice
        default: '0.5.0'
        options:
        - '0.5.0'

permissions:
  packages: write
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Clone source repo
      run: |-
        git clone https://github.com/twitter/twemproxy.git
        cd twemproxy
        git checkout --detach refs/tags/${{ inputs.tag }}

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build base image
      working-directory: ./twemproxy
      run: make -f ../Makefile build IMAGE_NAME=nutcracker IMAGE_TAG=${{ inputs.tag }}

    - name: Build final image
      run: make build IMAGE_NAME=${{ env.IMAGE }} IMAGE_TAG=${{ inputs.tag }} ARGS="--build-arg BUILDER=nutcracker:${{ inputs.tag }}"

    - name: Push docker image
      run: make push IMAGE_NAME=${{ env.IMAGE }} IMAGE_TAG=${{ inputs.tag }}
